feat: navigator on main page
loopnyapy/first_week pull request #2
Opened 2022-01-07 19:08 UTC by loopnyapy

feat: four squares page
feat: navigation on pages

2022-01-08 04:53 UTC, dkrutskikh requested changes

2022-01-08 04:53 UTC, dkrutskikh commented on lib/presentation/widgets/custom_appbar.dart
> +          : Container(),
@loopnyapy зачем тут контейнер, вроде как можно передать null

2022-01-08 04:53 UTC, dkrutskikh commented on lib/presentation/main/widgets/menu_item.dart
> +  final Function onTap;
@loopnyapy сейчас судя по твоему коду onTap принимает dynamic и возвращает dynamic. Давай типизируем эти места

2022-01-08 04:53 UTC, dkrutskikh commented on lib/presentation/main/widgets/menu_item.dart
> +    return InkWell(
@loopnyapy давай переедем на кнопку

2022-01-08 04:53 UTC, dkrutskikh commented on lib/presentation/four_squares/widgets/square.dart
> +class Square extends StatefulWidget {
@loopnyapy два вопроса:

1) почему StatefulWidget тк в state только функция build?
2) почему квадрат безразмерный?

2022-01-08 04:53 UTC, dkrutskikh commented on lib/presentation/four_squares/four_squares_page.dart
> +            color: generateColor(),
@loopnyapy получается что каждую перерисовку виджета у тебя будет новый цвет, это точно то что ты хотел получить?

2022-01-08 09:34 UTC, loopnyapy commented on lib/presentation/widgets/custom_appbar.dart
> +          : Container(),
нулл убирает это пробел на месте иконки
![image](https://user-images.githubusercontent.com/62483370/148639323-03652261-93a2-4bb1-a7df-148639ba820c.png)
![image](https://user-images.githubusercontent.com/62483370/148639338-da58a9b7-2dd1-46d6-9f24-dcef78988e2c.png)

2022-01-08 10:31 UTC, loopnyapy commented on lib/presentation/four_squares/widgets/square.dart
> +class Square extends StatefulWidget {
1. Да, исправил, вообще этот виджет даже не использовал в этом пр, поэтому не заметил.
2. Чтобы они резиновые были, гридом все делится на квадраты, а их размеры автоматом растягиваются на весь экран

2022-01-08 10:51 UTC, dkrutskikh requested changes

2022-01-08 10:51 UTC, dkrutskikh commented on lib/presentation/four_squares/four_squares_page.dart
> +// ignore_for_file: prefer_const_constructors
@loopnyapy не надо игнорировать это предупреждение, очень много оптимизаций основаны на константности данных

2022-01-08 10:51 UTC, dkrutskikh commented on lib/presentation/four_squares/four_squares_page.dart
> +  List<Square> currentSquareList = [];
@loopnyapy не стоит класть в состояние виджеты, их надо создавать в build функции

2022-01-08 10:54 UTC, loopnyapy commented on lib/presentation/four_squares/four_squares_page.dart
> +// ignore_for_file: prefer_const_constructors
ой, это я случайно :0 исправлю

2022-01-08 11:36 UTC, loopnyapy commented
а если цвета хранить и по ним генерировать?

2022-01-10 13:37 UTC, dkrutskikh approved these changes

2022-01-10 13:41 UTC, merged