feat: async query page
loopnyapy/first_week pull request #5
Opened 2022-01-15 17:08 UTC by loopnyapy

fix: surf lint setup
fix: of surf lint suggestions
![Simulator Screen Shot - iPhone 13 - 2022-01-15 at 20 04 49](https://user-images.githubusercontent.com/62483370/149630817-1e48d363-01a0-4f88-80c5-1fa784f61962.png)

2022-01-15 19:22 UTC, loopnyapy commented
@dkrutskikh добавил try catch и runZonedGuarded для ловли и там вопрос в тудушке: как правильно их выводить в ui?

2022-01-15 20:19 UTC, dkrutskikh requested changes

2022-01-15 20:19 UTC, dkrutskikh commented on lib/main.dart
> +      // TODO: как правильно ловить ошибки для отображения?
@loopnyapy я обычно логирую их

2022-01-15 20:19 UTC, dkrutskikh commented on lib/model/page.dart
> +  const Page({required this.name, required this.routeWidget});
@loopnyapy у тебя хорошая практика - отделять поля и конструктор пустой строкой. А еще ты то добавляешь trailing comma, то - нет

2022-01-15 20:19 UTC, dkrutskikh commented on lib/data/photos_data_source.dart
> +class PhotosDataSourceImpl implements PhotosDataSource {
@loopnyapy лучше 1 файл - 1 класс

2022-01-15 20:19 UTC, dkrutskikh commented on lib/data/photos_data_source.dart
> +        Uri.parse('httpss://jsonplaceholder.typicode.com/photos'),
@loopnyapy странный протокол, это точно работает?

2022-01-15 20:19 UTC, dkrutskikh commented on lib/model/photo/photo_card.dart
> +  PhotoCard({
@loopnyapy почему тут не константный конструктор?

2022-01-15 20:40 UTC, loopnyapy commented on lib/data/photos_data_source.dart
> +        Uri.parse('httpss://jsonplaceholder.typicode.com/photos'),
@dkrutskikh а, да, это я ошибки пытался тестить, забыл убрать

2022-01-15 20:41 UTC, loopnyapy commented on lib/model/page.dart
> +  const Page({required this.name, required this.routeWidget});
@dkrutskikh если не длинная строка обычно не ставлю :0 хорошо, буду следить

2022-01-16 08:27 UTC, loopnyapy commented
@dkrutskikh не стал делать логер никакой, оставил как есть - в консоль сыпятся ошибки. для такого маленького приложения подумал будет лишним

2022-01-17 20:11 UTC, dkrutskikh approved these changes

2022-01-18 12:04 UTC, merged